name: PRISM Frequent Pipeline

on:
  schedule:
    # Runs every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch:   # allows manual trigger from the Actions tab

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run PRISM pipeline
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}   # optional, if you use X fetcher
        run: |
          python prism_daily_pipeline.py
