- type: youtube
  label: "Mexico Senate – Debate on Energy Reform"
  url: "https://www.youtube.com/watch?v=G6C2sSYV9fU"

- type: youtube
  label: "Mexico Chamber of Deputies – Plenary Session"
  url: "https://www.youtube.com/watch?v=vx7gDJfaivg"

- type: youtube
  label: "California Senate – Water & Agriculture Hearing"
  url: "https://www.youtube.com/watch?v=4U1A7K91W0U"

- type: youtube
  label: "Texas House – Energy Grid & Market Stability"
  url: "https://www.youtube.com/watch?v=6M2OQm6jv1o"

- type: youtube
  label: "New York State Assembly – Budget Hearing"
  url: "https://www.youtube.com/watch?v=NGaSOfFjtxI"

- type: youtube
  label: "US Senate – Federal Reserve Oversight Hearing"
  url: "https://www.youtube.com/watch?v=E7yQxtYk95M"

- type: youtube
  label: "US House – Agriculture Committee Hearing"
  url: "https://www.youtube.com/watch?v=OYe9zFVX1Bg"

- type: youtube
  label: "Parliament of Canada – Carbon Pricing Debate"
  url: "https://www.youtube.com/watch?v=ST0ShXxq8sk"

- type: youtube
  label: "Ontario Legislative Assembly – Energy & Finance Committee"
  url: "https://www.youtube.com/watch?v=U8X1u6p_0tI"

- type: youtube
  label: "British Columbia Legislature – Climate Change Debate"
  url: "https://www.youtube.com/watch?v=vlU6yRrG9iw"

