name: run-prism-pipeline

on:
  schedule:
    - cron: "0 */6 * * *"   # Runs every 6 hours
  workflow_dispatch:         # Allow manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run PRISM pipeline
        run: python prism_daily_pipeline.py
