name: RHIS Pipeline

on:
  schedule:
    - cron: "0 */6 * * *"   # run every 6 hours
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2 libjpeg-turbo-progs poppler-utils

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm

      - name: Run pipeline
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
          YOUTUBE_TRANSCRIPT_TOKEN: ${{ secrets.YOUTUBE_TRANSCRIPT_TOKEN }}
          CONGRESS_API_KEY: ${{ secrets.CONGRESS_API_KEY }}
        run: |
          python prism_daily_pipeline.py

