name: run-x-fetcher

on:
  schedule:
    - cron: "0 */4 * * *"   # every 4 hours
  workflow_dispatch:        # allow manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run PRISM pipeline
        run: python prism_daily_pipeline.py
